baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

[taxonomies]
  series = 'series'
  tag = 'tags'
  category = 'categories'

[params]
  author = "Alex Kaplan"
  description = "Thoughts on impact and engineering"
  defaultTheme = "auto"
  showBreadCrumbs = false
  showReadingTime = true
  ShowPostNavLinks = false

[menu]
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1
