baseURL = 'https://kaplanalex.github.io/blog/'
languageCode = 'en-us'
title = "Alex's blog"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  series = 'series'
  tag = 'tags'
  category = 'categories'

[params]
  author = "Alex Kaplan"
  description = "Thoughts on impact and engineering"
  defaultTheme = "auto"
  showBreadCrumbs = false
  showReadingTime = true
  ShowPostNavLinks = false

[menu]
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Series"
  url = "/series/"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3

[[menu.main]]
  name = "Newsletter"
  url = "/newsletter/"
  weight = 4
